django-second/webapp/post_comment/urls.py
from django.urls import path
from . import views

app_name = "app"

urlpatterns = [
    path('',views.index, name='index'),
    path('demo/', views.demo, name="demo"),
    path('service/', views.service, name="service"),
    path('chart', views.line_chart, name='line_chart'),
    path('chartJSON', views.line_chart_json, name='line_chart_json'),
    path('qna/', views.post_list, name='qna'),
    path('qna/<int:pk>/', views.detail, name='detail'),
    path('answer/create/<int:pk>/', views.comments_create, name='comments_create'),
    path('post/create/', views.posts_create, name='posts_create'),
    path('post/modify/<int:pk>/', views.posts_modify, name='posts_modify'),
    path('post/delete/<int:pk>/', views.posts_delete, name='posts_delete'),
    path('comment/modify/<int:pk>/', views.comments_modify, name='comments_modify'),
    path('comment/delete/<int:pk>/', views.comments_delete, name='comments_delete'),

]

django-second/webapp/user/urls.py
from django.urls import path
from . import views

# app_name = 'user'
app_name = 'app'
urlpatterns = [
    path('',views.index, name='index'),
    # path('demo/', views.demo, name="demo"),
    # path('service/', views.service, name="service"),
    # path('profile/', views.profile, name="profile"),
    # path('profile/userinfo/', views.userinfo, name="userinfo"),
    path('login/', views.login, name='login'),
    # path('password/', views.password, name='password'),
    # path('register/', views.register, name='register'),
]

django-second/webapp/webapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post_comment.urls')),
    path('cam/',include('webcam_app.urls')),
    path('accounts/', include('account.urls')),
]
# from app.views import index, question_insert

django-second/webapp/post_comment/models.py
from account.models import User
from django.db import models

# 질문란
class BoardPost(models.Model):
    # CASCADE : User를 삭제하면 관련있는 모든 현재 테이블의 데이터 삭제
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.TextField()
    create_at = models.DateTimeField(null=True, blank=True,auto_now_add=True)
    update_at = models.DateTimeField(null=True, blank=True,auto_now=True)
    # 작성한 질문이 제목으로 보여지게 함
    def __str__(self):
        return self.title
    class Meta:
        db_table = 'boardpost'
        verbose_name_plural = "boardPosts"

# 댓글란
class BoardComment(models.Model):
    boardpost=models.ForeignKey(BoardPost, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_at = models.DateTimeField(null=True, blank=True,auto_now_add=True)
    update_at = models.DateTimeField(null=True, blank=True,auto_now=True)
    
    # 작성한 답변이 제목으로 보여지게 함
    def __str__(self):
        return self.content

    class Meta:
        db_table = 'boardcomment'
        verbose_name_plural = "boardComments"

django-second/webapp/templates/answer_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 답변 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

django-second/webapp/templates/base.html
{% load static %}

<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">-->
    <link href="https://cdn.jsdelivr.net/npm/bootswatch@5.0.1/dist/lux/bootstrap.min.css" rel="stylesheet" crossorigin="anoymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/vendor.css' %}"> 
    <link rel="stylesheet" href="{% static 'css/mainstyle.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <title>EmoAI</title>

</head>
<body>
    <body id="top">
        <!-- page wrap
        ================================================== -->
        <div id="page" class="s-pagewrap">

{% include 'navbar.html' %}


{% block content %}


{% endblock %}


{% include 'footer.html' %}

 

<script src="{% static 'js/plugins.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

django-second/webapp/templates/boardpost_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ posts.title }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ posts.content }}</div>
            <div class="d-flex justify-content-end">
                {% if posts.update_at %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ posts.update_at }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ posts.user.username }}</div>
                    <div>{{ posts.create_at }}</div>
                </div>
            </div>
            <div class="my-3">
                {% if request.user == posts.user %}
                <a href="{% url 'app:posts_modify' posts.pk  %}" 
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{% url 'app:posts_delete' posts.pk  %}">삭제</a>    
               {% endif %}
            </div>
        </div>
    </div>
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{posts.boardcomment_set.count}}개의 답변이 있습니다.</h5>
    {% for comment in posts.boardcomment_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ comment.content }}</div>
            <div class="d-flex justify-content-end">
                {% if comment.update_at %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ comment.update_at }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ comment.user.username }}</div>
                    <div>{{ comment.create_at }}</div>
                </div>
            </div>
            <div class="my-3">
                {% if request.user == comment.user %}
                <a href="{% url 'app:comments_modify' comment.pk  %}" 
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary "
                   data-uri="{% url 'app:comments_delete' comment.pk  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{% url 'app:comments_create' posts.pk %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <label for="{{ form.content.id_for_label }}">답변내용</label>
            {{ form.content }}
            </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>






{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

django-second/webapp/templates/boardpost_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="title" id="title"
                   value="{{ form.title.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

django-second/webapp/templates/boardpost_list.html
{% extends 'base.html' %}
{% load qna_filter %}
{% block content %}
<div class="container my-3">
    <div class="table-responsive col-md-10 offset-md-1"> 
    <table class="table">
        <thead>
        <tr class="text-center table-dark">
            <th>번호</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if posts_list %}
        {% for posts in posts_list %}
        <tr class="text-center">
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ posts_list.paginator.count|sub:posts_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td class="text-start">
                <a href="{% url 'app:detail' posts.pk %}">{{ posts.title }}</a>
                {% if posts.boardcomment.count  > 0 %}
                <span class="text-danger small mx-2">{{ posts.boardcomment.count }}</span>
                {% endif %} 
            </td>
            <td>{{ posts.user.userid }}</td>  <!-- 글쓴이 추가 -->
            <td>{{ posts.create_at }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if boardpost_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ boardpost_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in boardpost_list.paginator.page_range %}
        {% if page_number >= boardpost_list.number|add:-5 and page_number <= boardpost_list.number|add:5 %}
        {% if page_number == boardpost_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if boardpost_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ boardpost_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <a href="{% url 'app:posts_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
{% endblock %}

django-second/webapp/templates/comments_form.html
{% extends 'base.html' %}

{% block content %}

<!-- comment_form.html -->
<form method="post" action="{% url 'app:comments_create' pk=Posts.pk %}">
    {% csrf_token %}
    <div class="form-group">
        {{ form.content.label_tag }}
        {{ form.content }}
        {% if form.content.errors %}
            <div class="invalid-feedback">
                {% for error in form.content.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
        {% endif %}
    </div>
    <button type="submit" class="btn btn-primary">댓글 등록</button>
</form>






{% endblock %}

django-second/webapp/templates/demo.html
  {% extends 'base.html' %}
  {% load static %}
  {% block content %}
    <body>
        <div class="container">
            <div class="row justify-content-center ">
            <div class="col-4">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae voluptates rerum quis! Voluptatibus, quod fugit tenetur et, in magnam tempore quas reprehenderit voluptas illum adipisci blanditiis? Beatae placeat facilis ipsa.
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quos sequi incidunt aliquam nostrum excepturi eveniet debitis placeat ipsa consequuntur rerum! Dolore id distinctio, autem neque non facere natus ut soluta!
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Possimus, cum eius, neque, sapiente magni architecto delectus sint odio ullam repudiandae hic commodi. Ducimus saepe vero accusamus sint beatae explicabo adipisci.
            </div>
            <div class="col-4">
                <table class="table table-warning">
                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">First</th>
                        <th scope="col">Last</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <th scope="row">1</th>
                        <td>Mark</td>
                        <td>Otto</td>
                      </tr>
                      <tr>
                        <th scope="row">2</th>
                        <td>Jacob</td>
                        <td>Thornton</td>
                      </tr>
                      <tr>
                        <th scope="row">3</th>
                        <td>Jacob</td>
                        <td>Thornton</td>
                      </tr>
                      <tr>
                        <th scope="row">4</th>
                        <td>Jacob</td>
                        <td>Thornton</td>
                      </tr>
                      <tr>
                        <th scope="row">5</th>
                        <td>Jacob</td>
                        <td>Thornton</td>
                      </tr>
                      <tr>
                        <th scope="row">6</th>
                        <td>Jacob</td>
                        <td>Thornton</td>
                      </tr>
                      <tr>
                        <th scope="row">7</th>
                        <td>Jacob</td>
                        <td>Thornton</td>
                      </tr>
                    </tbody>
                  </table>
            </div>
            </div>
        </div>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-6"><button type="button" class="btn btn-warning">실시간 웹캠 시작</button></div>
            </div>
            </div>

        <!-- chartjs -->
        <div class="container">
            <h1>Some Line Charts loaded in Ajax!</h1>
        </div>
            <canvas id="myChart" width="500" height="200"></canvas>
    
            <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
            <script type="text/javascript" src="{% static 'js/Chart.min.js' %}"></script>
            <script type="text/javascript">
                $.get("{% url 'app:line_chart_json' %}", function(data) {
                    var ctx = $("#myChart").get(0).getContext("2d");
                    new Chart(ctx, {
                        type: 'line', data: data
                    });
                });
            </script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    </body>
{% endblock %}

django-second/webapp/templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
{% endif %}

django-second/webapp/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <body>
        <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-5">
                                <div class="card shadow-lg border-0 rounded-lg mt-5">
                                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Login</h3></div>
                                    <div class="card-body">

                                        {% if message %}
                                        <div class="alert alert-danger">{{ message }}</div>
                                        {% endif %}
                                        
                                        <form method="POST" action=""> 
                                            {% csrf_token %}
                                            <div class="form-floating mb-3">
                                                <input class="form-control" name="userid" id="inputEmail" type="text" placeholder="name@example.com" />
                                                <label for="inputEmail">userid</label>
                                            </div>
                                            <div class="form-floating mb-3">
                                                <input class="form-control" name="password" id="inputPassword" type="password" placeholder="Password" />
                                                <label for="inputPassword">Password</label>
                                            </div>
                                            <div class="form-check mb-3">
                                                <input class="form-check-input" id="inputRememberPassword" type="checkbox" value="" />
                                                <label class="form-check-label" for="inputRememberPassword">Remember Password</label>
                                            </div>
                                            <div class="d-flex align-items-center justify-content-between mt-4 mb-0">
                                                <a class="small" href="{% url 'password_reset' %}">Forgot Password?</a>
                                                <button class="btn btn-primary btn-block" >Login</button>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="card-footer text-center py-3">
                                        <div class="small"><a href="{% url 'signup' %}">Need an account? Sign up!</a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="js/scripts.js"></script>
    </body>
{% endblock %}

django-second/webapp/templates/navbar.html
<div class="b-example-divider"></div>
<div class="container">
<nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
      </a>
      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="/" class="nav-link px-2 link-secondary">Home</a></li>
        <li><a href="/#about" class="nav-link px-2 link-dark">About</a></li>
        <li><a href="{% url 'app:demo' %}" class="nav-link px-2 link-dark">Demo</a></li>
        <li><a href="{% url 'app:service' %}" class="nav-link px-2 link-dark">Service</a></li>
        <li><a href="{% url 'app:qna' %}" class="nav-link px-2 link-dark">QnA</a></li>
        <li><a href="/#contact_us" class="nav-link px-2 link-dark">Contact</a></li>
      </ul>
      <div class="d-flex col-md-3">
        {% if user.is_authenticated %}
        {{ user.userid }}님
        <a class=" btn-outline-primary me-2" href="{% url 'logout' %}" role="button">Logout</a>
        {% else %}
        <a class="btn btn-outline-primary me-2" href="{% url 'login' %}" role="button">Login</a>
        <a class="btn btn-primary" href="{% url 'signup' %}" role="button">sign-up</a>
        {% endif %}
        <!-- button 색상 변경 style="background-color: grey" 옵션 추가-->
      </div>
    </header>
  </div>

django-second/webapp/templates/service.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <body>
        <div>
            <div class="container text-center">
                <div class="row justify-content-center">
                    <div class="col-4">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae voluptates rerum quis! Voluptatibus, quod fugit tenetur et, in magnam tempore quas reprehenderit voluptas illum adipisci blanditiis? Beatae placeat facilis ipsa.
                        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quos sequi incidunt aliquam nostrum excepturi eveniet debitis placeat ipsa consequuntur rerum! Dolore id distinctio, autem neque non facere natus ut soluta!
                        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Possimus, cum eius, neque, sapiente magni architecto delectus sint odio ullam repudiandae hic commodi. Ducimus saepe vero accusamus sint beatae explicabo adipisci.
                    </div>

                    <div class="col-4">
                        
                        <table class="table table-warning">
                            <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">First</th>
                                <th scope="col">Last</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <th scope="row">1</th>
                                <td>Mark</td>
                                <td>Otto</td>
                            </tr>
                            <tr>
                                <th scope="row">2</th>
                                <td>Jacob</td>
                                <td>Thornton</td>
                            </tr>
                            <tr>
                                <th scope="row">3</th>
                                <td>Jacob</td>
                                <td>Thornton</td>
                            </tr>
                            <tr>
                                <th scope="row">4</th>
                                <td>Jacob</td>
                                <td>Thornton</td>
                            </tr>
                            <tr>
                                <th scope="row">5</th>
                                <td>Jacob</td>
                                <td>Thornton</td>
                            </tr>
                            <tr>
                                <th scope="row">6</th>
                                <td>Jacob</td>
                                <td>Thornton</td>
                            </tr>
                            <tr>
                                <th scope="row">7</th>
                                <td>Jacob</td>
                                <td>Thornton</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="container text-center">
                <div class="row justify-content-center">
                    <div class="col-4">
                            <button type="button" class="btn btn-warning">실시간 웹캠 시작</button>
                    </div>
                    <div class="col-4">
                        <div class="input-group mb-3">
                            <input type="file" class="form-control" id="inputGroupFile02">
                            <label class="input-group-text" for="inputGroupFile02">Upload</label>
                          </div>
                    </div>
                </div>
            </div>


        </div>

    <div class="container text-center">
        <div class="row">
            <div class="col">
                <h1>Some Line Charts loaded in Ajax!</h1>

                <canvas id="myChart" width="500" height="200"></canvas>
        
                <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
                <script type="text/javascript" src="{% static 'js/Chart.min.js' %}"></script>
                <script type="text/javascript">
                    $.get("{% url 'app:line_chart_json' %}", function(data) {
                        var ctx = $("#myChart").get(0).getContext("2d");
                        new Chart(ctx, {
                            type: 'line', data: data
                        });
                    });
                </script>
                <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
                <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
        
                <div class="col">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae voluptates rerum quis! Voluptatibus, quod fugit tenetur et, in magnam tempore quas reprehenderit voluptas illum adipisci blanditiis? Beatae placeat facilis ipsa.
                    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quos sequi incidunt aliquam nostrum excepturi eveniet debitis placeat ipsa consequuntur rerum! Dolore id distinctio, autem neque non facere natus ut soluta!
                    Lorem ipsum dolor, sit amet consectetur adipisicing elit. Possimus, cum eius, neque, sapiente magni architecto delectus sint odio ullam repudiandae hic commodi. Ducimus saepe vero accusamus sint beatae explicabo adipisci.
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}

<!-- 모달 -->
<div class="modal" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Modal title</h5>
          <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>Modal body text goes here.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>