django-4/webapp/account/urls.py
from django.urls import path 
from . import views

app_name = "account"

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
]

django-4/webapp/app/urls.py
from django.urls import path
from . import views

app_name = "app"

urlpatterns = [
    path('',views.index, name='index'),
    path('demo/', views.demo, name="demo"),
    path('service/', views.service, name="service"),
    path('profile/', views.profile, name="profile"),
    path('profile/userinfo/', views.userinfo, name="userinfo"),
    path('password/', views.password, name='password'),
    path('qna/', views.password, name='qna'),
    # path('chart', views.line_chart, name='line_chart'),
    # path('chartJSON', views.line_chart_json, name='line_chart_json'),
]

django-4/webapp/webapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('cam/',include('webcam_app.urls')),
    path('accounts/', include('account.urls')),
]
# from app.views import index, question_insert

django-4/webapp/templates/base.html
<!doctype html>
{% load static %}
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/vendor.css' %}"> 
    <link rel="stylesheet" href="{% static 'css/mainstyle.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <title>EmoAI</title>
</head>
<body>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% include 'navbar.html' %}

{% block content %}


{% endblock %}

{% include 'footer.html' %}



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'js/scripts.js' %}"></script>    
<!-- Bootstrap JS -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

django-4/webapp/templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

django-4/webapp/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <!-- # site-content
        ================================================== -->
        <section id="content" class="s-content">
            <!-- intro
            ----------------------------------------------- -->
            <section id="intro" class="s-intro target-section">
                <img src="{% static 'img/intro.jpg' %}"> </img>
                <div class="s-intro__bg">
                </div>
                <div class="row s-intro__content">
                    <div class="s-intro__content-bg">
                    </div>
                    <div class="column lg-12 s-intro__content-inner">
                        <h1 class="s-intro__content-title">
                        We provide creative <br>
                        solutions to turn your <br>
                        ideas into digital reality.
                        </h1>

                        <div class="s-intro__content-buttons">
                            <a href="#download" class="btn btn--stroke s-intro__content-btn smoothscroll"> Experience Our Service</a>
                            <a href="https://player.vimeo.com/video/14592941?color=f26522&title=0&byline=0&portrait=0" class="s-intro__content-video-btn">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgba(0, 0, 0, 1);transform: ;msFilter:;"><path d="M7 6v12l10-6z"></path></svg>
                            </a>
                        </div>
                        
                    </div> <!-- s-intro__content-inner -->

                </div> <!-- s-intro__content -->

                <div class="s-intro__scroll-down">
                    <a href="#about" class="smoothscroll">
                        <span>Scroll Down</span>
                    </a>
                </div> <!-- s-intro__scroll-down -->

            </section> <!-- end s-intro -->

            <!-- /#about
            ----------------------------------------------- -->
            <section id="about" class="s-about target-section">
                <div class="row section-header" data-num="01">
                    <h3 class="column lg-12 section-header__pretitle pretitle text-pretitle">Who We Are</h3>
                    <div class="column lg-6 stack-on-1100 section-header__primary">
                        <h2 class="title text-display-1">
                        EmoAI는 감정분석에 특화된 웹서비스를 제공하는 회사입니다. 
                        </h2>
                    </div>
                    <div class="column lg-6 stack-on-1100 section-header__secondary">
                        <p class="desc">
                        저희의 목표는 고객이 제공한 발화를 분석하여 발화자의 감정 상태를 정확하게 
                        파악하여, 보다 효과적인 커뮤니케이션과 의사결정을 돕는 것입니다.
                        </p>
                    </div>
                </div> <!-- end section-header -->

                <div class="row services-list list-block block-lg-one-half block-tab-whole">

                    <div class="column list-block__item">
                        <div class="list-block__title">
                            <div class="list-block__icon">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgba(0, 0, 0, 1);transform: ;msFilter:;"><path d="m6.516 14.323-1.49 6.452a.998.998 0 0 0 1.529 1.057L12 18.202l5.445 3.63a1.001 1.001 0 0 0 1.517-1.106l-1.829-6.4 4.536-4.082a1 1 0 0 0-.59-1.74l-5.701-.454-2.467-5.461a.998.998 0 0 0-1.822 0L8.622 8.05l-5.701.453a1 1 0 0 0-.619 1.713l4.214 4.107zm2.853-4.326a.998.998 0 0 0 .832-.586L12 5.43l1.799 3.981a.998.998 0 0 0 .832.586l3.972.315-3.271 2.944c-.284.256-.397.65-.293 1.018l1.253 4.385-3.736-2.491a.995.995 0 0 0-1.109 0l-3.904 2.603 1.05-4.546a1 1 0 0 0-.276-.94l-3.038-2.962 4.09-.326z"></path></svg>
                            </div>
                            <h3 class="h5">Tech</h3>
                        </div>
                        <div class="list-block__text">
                            <p>
                            저희는 자연어처리(Natural Language Processing) 기술을 활용하여 
                            고객이 제공한 발화를 분석하며, 
                            인공지능 기술을 적용하여 정확한 감정분석 결과를 제공합니다.
                            </p>
                        </div>
                    </div> <!-- end list-block__item -->

                    <div class="column list-block__item">
                        <div class="list-block__title">
                            <div class="list-block__icon">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgba(0, 0, 0, 1);transform: ;msFilter:;"><path d="m6.516 14.323-1.49 6.452a.998.998 0 0 0 1.529 1.057L12 18.202l5.445 3.63a1.001 1.001 0 0 0 1.517-1.106l-1.829-6.4 4.536-4.082a1 1 0 0 0-.59-1.74l-5.701-.454-2.467-5.461a.998.998 0 0 0-1.822 0L8.622 8.05l-5.701.453a1 1 0 0 0-.619 1.713l4.214 4.107zm2.853-4.326a.998.998 0 0 0 .832-.586L12 5.43l1.799 3.981a.998.998 0 0 0 .832.586l3.972.315-3.271 2.944c-.284.256-.397.65-.293 1.018l1.253 4.385-3.736-2.491a.995.995 0 0 0-1.109 0l-3.904 2.603 1.05-4.546a1 1 0 0 0-.276-.94l-3.038-2.962 4.09-.326z"></path></svg>
                            </div>
                            <h3 class="h5">Privacy</h3>
                        </div>
                        <div class="list-block__text">
                            <p>
                            개인정보 보호와 안전한 서비스 제공을 위해 최신 보안기술을 적용하고 있습니다.
                            </p>
                        </div>
                    </div> <!-- end list-block__item -->
        
                    <div class="column list-block__item">
                        <div class="list-block__title">
                            <div class="list-block__icon">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgba(0, 0, 0, 1);transform: ;msFilter:;"><path d="m6.516 14.323-1.49 6.452a.998.998 0 0 0 1.529 1.057L12 18.202l5.445 3.63a1.001 1.001 0 0 0 1.517-1.106l-1.829-6.4 4.536-4.082a1 1 0 0 0-.59-1.74l-5.701-.454-2.467-5.461a.998.998 0 0 0-1.822 0L8.622 8.05l-5.701.453a1 1 0 0 0-.619 1.713l4.214 4.107zm2.853-4.326a.998.998 0 0 0 .832-.586L12 5.43l1.799 3.981a.998.998 0 0 0 .832.586l3.972.315-3.271 2.944c-.284.256-.397.65-.293 1.018l1.253 4.385-3.736-2.491a.995.995 0 0 0-1.109 0l-3.904 2.603 1.05-4.546a1 1 0 0 0-.276-.94l-3.038-2.962 4.09-.326z"></path></svg>
                            </div>
                            <h3 class="h5">Additional service</h3>
                        </div>
                        <div class="list-block__text">
                            <p>
                            고객의 다양한 요구에 부응하기 위해, 감정분석 결과를 시각화하고, 보고서로 제공하는 등의 부가 서비스를 제공합니다.
                            </p>
                        </div>
                    </div> <!-- end list-block__item -->
        
                    <div class="column list-block__item">
                        <div class="list-block__title">
                            <div class="list-block__icon">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgba(0, 0, 0, 1);transform: ;msFilter:;"><path d="m6.516 14.323-1.49 6.452a.998.998 0 0 0 1.529 1.057L12 18.202l5.445 3.63a1.001 1.001 0 0 0 1.517-1.106l-1.829-6.4 4.536-4.082a1 1 0 0 0-.59-1.74l-5.701-.454-2.467-5.461a.998.998 0 0 0-1.822 0L8.622 8.05l-5.701.453a1 1 0 0 0-.619 1.713l4.214 4.107zm2.853-4.326a.998.998 0 0 0 .832-.586L12 5.43l1.799 3.981a.998.998 0 0 0 .832.586l3.972.315-3.271 2.944c-.284.256-.397.65-.293 1.018l1.253 4.385-3.736-2.491a.995.995 0 0 0-1.109 0l-3.904 2.603 1.05-4.546a1 1 0 0 0-.276-.94l-3.038-2.962 4.09-.326z"></path></svg>
                            </div>
                            <h3 class="h5">Effort</h3>
                        </div>
                        <div class="list-block__text">
                            <p>
                            고객의 피드백을 적극 수용하여 보다 나은 서비스를 제공하기 위해 노력하고 있습니다.
                            </p>
                        </div>
                    </div> <!-- end list-block__item -->

                </div> <!-- end process-list -->
                
                <br>
                <br>
                
                <!-- what we do -->
                <div class="row section-header" data-num="02">
                    <h3 class="column lg-12 section-header__pretitle text-pretitle">What We Do</h3>
                </div> <!-- end section-header -->

                <div class="row process-list list-block show-ctr block-lg-one-half block-tab-whole">

    
                    <div class="column list-block__item">
                        <div class="list-block__title">
                            <h3 class="h5">Consulting</h3>
                        </div>
                        <div class="list-block__img">
                            <p>
                            <img src="{% static 'img/상담.jpg' %}"></img>
                            </p>
                        </div>
                    </div> <!-- end list-block__item -->
        
                    <div class="column list-block__item">
                        <div class="list-block__title">
                            <h3 class="h5"> Emotion Analysis</h3>
                        </div>
                        <div class="list-block__img">
                            <p>
                            <img src="{% static 'img/분석.jpg' %}"></img>
                            </p>
                        </div>
                    </div> <!-- end list-block__item -->
        
                    <div class="column list-block__item">
                        <div class="list-block__title">
                            <h3 class="h5">Get Idea</h3>
                        </div>
                        <div class="list-block__img">
                            <p>
                            <img src="{% static 'img/아이디어.jpg' %}"></img>
                            </p>
                        </div>
                    </div> <!-- end list-block__item -->
        
                    <div class="column list-block__item">
                        <div class="list-block__title">
                            <h3 class="h5">Solution</h3>
                        </div>
                        <div class="list-block__img">
                            <p>
                            <img src="{% static 'img/솔루션.jpg' %}"></img>
                            </p>
                        </div>
                    </div> <!-- end list-block__item -->
                </div> <!-- end process-list -->
            </section> <!-- end /#about -->


        <section id="contact_us">
        <div class="row section-header" data-num="03">
                <h3 class="column lg-12 section-header__pretitle text-pretitle">Get In Touch</h3>
                <div class="column lg-6 stack-on-1100 section-header__primary">
                    <h2 class="title text-display-1">
                    Have an idea or an epic project in mind? 
                    <a href="mailto:#0" title="">hello@emoai.com</a>
                    </h2>
                </div>    
                <div class="column lg-6 stack-on-1100 section-header__secondary">
                    
                    <div class="contact-block">
                        <h6>Where To Find Us</h6>
                        <p>
                        서울시 서초구 효령로 335 <br>
                        </p>
                    </div>

                    <div class="contact-block">
                        <h6>Contact Infos</h6>
                        <ul class="contact-list">
                            <li><a href="tel:000-000-0000">+000 000 0000</a></li>
                        </ul>
                    </div>

                </div>
            </div> <!-- end section-header -->
        </section>

{% endblock %}

django-4/webapp/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <body>
        <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-5">
                                <div class="card shadow-lg border-0 rounded-lg mt-5">
                                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Login</h3></div>
                                    <div class="card-body">
                                        <form>
                                            <div class="form-floating mb-3">
                                                <input class="form-control" id="inputEmail" type="email" placeholder="name@example.com" />
                                                <label for="inputEmail">Email address</label>
                                            </div>
                                            <div class="form-floating mb-3">
                                                <input class="form-control" id="inputPassword" type="password" placeholder="Password" />
                                                <label for="inputPassword">Password</label>
                                            </div>
                                            <div class="form-check mb-3">
                                                <input class="form-check-input" id="inputRememberPassword" type="checkbox" value="" />
                                                <label class="form-check-label" for="inputRememberPassword">Remember Password</label>
                                            </div>
                                            <div class="d-flex align-items-center justify-content-between mt-4 mb-0">
                                                <a class="small" href="{% url 'app:password' %}">Forgot Password?</a>
                                                <button class="btn btn-primary" >Login</button>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="card-footer text-center py-3">
                                        <div class="small"><a href="{% url 'account:signup' %}">Need an account? Sign up!</a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="js/scripts.js"></script>
    </body>
{% endblock %}

django-4/webapp/templates/navbar.html
<div class="b-example-divider"></div>
<div class="container">
<nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
      </a>
      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="/" class="nav-link px-2 link-secondary">Home</a></li>
        <li><a href="/#about" class="nav-link px-2 link-dark">About</a></li>
        <li><a href="{% url 'app:demo' %}" class="nav-link px-2 link-dark">Demo</a></li>
        <li><a href="{% url 'app:service' %}" class="nav-link px-2 link-dark">Service</a></li>
        {% comment %} <li><a href="{% url 'app:question_list' %}" class="nav-link px-2 link-dark">QnA</a></li> {% endcomment %}
        <li><a href="/#contact_us" class="nav-link px-2 link-dark">Contact</a></li>
      </ul>
      <div class="d-flex col-md-3">
        {% if user.is_authenticated %}
        <a class=" btn-outline-primary me-2" href="{% url 'app:index' %}" role="button">Logout</a>
        {% else %}
        <a class="btn btn-outline-primary me-2" href="{% url 'account:login' %}" role="button">Login</a>
        {% endif %}
        <a class="btn btn-primary" href="{% url 'account:signup' %}" role="button">sign-up</a>
        <!-- button 색상 변경 style="background-color: grey" 옵션 추가-->
      </div>
    </header>
  </div>

django-4/webapp/templates/password.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <body>
        <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                <main class="container">
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-5">
                                <div class="card shadow-lg border-0 rounded-lg mt-5">
                                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Password Recovery</h3></div>
                                    <div class="card-body">
                                        <div class="small mb-3 text-muted">Enter your email address and we will send you a link to reset your password.</div>
                                        <form>
                                            <div class="form-floating mb-3">
                                                <input class="form-control" id="inputEmail" type="email" placeholder="name@example.com" />
                                                <label for="inputEmail">Email address</label>
                                            </div>
                                            <div class="d-flex align-items-center justify-content-between mt-4 mb-0">
                                                <a class="small" href="{% url 'account:login' %}">Return to login</a>
                                                <a class="btn btn-primary" href="login.html">Reset Password</a>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="card-footer text-center py-3">
                                        <div class="small"><a href="{% url 'account:signup' %}">Need an account? Sign up!</a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
            
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="js/scripts.js"></script>
    </body>
{% endblock %}

django-4/webapp/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section style="background-color: #ffffff;">
  <div class="container py-5">
    <div class="row">
      <div class="col">
        <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
          <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">User Profile</li>
          </ol>
        </nav>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-4">
        <div class="card mb-4">
          <div class="card-body text-center">
            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp" alt="avatar"
              class="rounded-circle img-fluid" style="width: 150px;">
            <h5 class="my-3">John Smith</h5>
            <p class="text-muted mb-1">아이디</p>
            <p class="text-muted mb-4"></p>
            <div class="d-flex justify-content-center mb-2">
              <a class="btn btn-primary" href="{% url 'app:userinfo' %}" role="button">회원정보 수정</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-8 pt-">
        <div class="card mb-4">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">이름</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">Johnatan Smith</p>
              </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">비밀번호</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">ooooooo</p>
                  <!-- <button type="button" class="btn btn-light" class="btn float-right" >비밀번호 변경</button> 회원수정페이지에 넣을 기능--> 
                </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">이메일</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">example@example.com</p>
              </div>
            </div>
            <hr>
            <!-- <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">업종</p>
              </div>
                  <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                      업종
                    </button>
                    <ul class="dropdown-menu">
                      <li><button class="dropdown-item" type="button">병원/의원</button></li>
                      <li><button class="dropdown-item" type="button">Another action</button></li>
                      <li><button class="dropdown-item" type="button">Something else here</button></li>
                    </ul>
                  </div> 회원수정페이지에 넣을 기능
              <div class="col-sm-9">
                <p class="text-muted mb-0">(097) 234-5678</p>
              </div>
            </div>
            <hr>   업종이 필요할까요? -->
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">전화번호</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">(098) 765-4321</p>
              </div>
            </div>
            <hr>
            <div class="row">

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

modal
<div class="modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Modal body text goes here.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

django-4/webapp/templates/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

django-4/webapp/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <body>
        <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-7">
                                <div class="card shadow-lg border-0 rounded-lg mt-5">
                                    <form method="POST"> {% csrf_token %} 
                                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Create Account</h3></div>
                                    <div class="card-body py-5">
                                        <form>
                                            <div class="d-flex justify-content-between">
                                                <div class="col form-floating">
                                                    <input name="userid" class="form-control d-grid" id="inputUserId" type="text" placeholder="Enter your ID" />
                                                    <label for="inputUserId">Userid</label>
                                                </div>
                                                <!-- <div class="col form-floating">
                                                    <input class="form-control d-grid" id="inputLastName" type="text" placeholder="Enter your last name" />
                                                    <label for="inputLastName">Last name</label>
                                                </div> -->
                                            </div>
                                            <div class="form-floating">
                                                <input name="password" class="form-control" id="inputPassword" type="password" placeholder="Create a password" />
                                                <label for="inputPassword">Password</label>
                                            </div>
                                            <div class="form-floating mb-3 mb-md-0">
                                                <input name="password2" class="form-control" id="inputPasswordConfirm" type="password" placeholder="Confirm password" />
                                                <label for="inputPasswordConfirm">Confirm Password</label>
                                            </div>
                                            <!-- 색 왜 안바뀌지? -->
                                            <div class="col form-floating">
                                                <input name="username" class="form-control" id="inputUserName" type="username" placeholder="Enter your name" />
                                                <label for="inputUserName">Username</label> 
                                            </div>
                                            <div class="form-floating">
                                                <input name="email" class="form-control" id="inputEmail" type="email" placeholder="name@example.com" />
                                                <label for="inputEmail">Email address</label>
                                            </div>
                                            <div class="mt-4 mb-0">
                                                <div class="d-grid"><button class="btn btn-primary btn-block" >Create Account</button></div>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="card-footer text-center py-2">
                                        <div class="small"><a href="{% url 'account:login' %}">Have an account? Go to login</a></div>
                                    </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="js/scripts.js"></script>
    </body>
{% endblock %}